### ISSUE TITLE
soroban-cli: promote all install methods in docs

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-cli#1083]
The soroban-cli is installable via a few mechanisms now:
- cargo install from source
- cargo bininstall from precompiled binary
- brew install via the stellar/homebrew-tap
- release binaries on github.com/stellar/soroban-tools

As far as I can tell we don't promote any of these installation methods other than the first in the soroban-docs or elsewhere.

**Comment by willemneal** [comment]
I say we push binstall as it helps install easily in CI and is cross-platform.

**Comment by stellarsaur** [comment]
We could mention all installation methods in the [GitHub README](https://github.com/stellar/soroban-tools/tree/main/cmd/soroban-cli) and [Soroban Docs](https://soroban.stellar.org/docs/getting-started/setup#install-the-soroban-cli), but recommend `cargo install` and `cargo bininstall` for the reasons @willemneal mentioned

**Comment by leighmcculloch** [comment]
Bininstall is helpful, but less so to developers who aren't Rust devs or advanced devs. For rust devs then `cargo install` and `cargo bininstall` fall on the same plane of convenience, and some will prefer one or the other. Promoting install methods needs to be focused on supporting all users wherever they're at, and `brew install` helps mac users, and ideally we add other install methods in the future like `scoop` for windows users, etc.

So I don't think we specifically need to push one install path over the other, but just surface them all.

**Comment by janewang** [comment]
PR to close https://github.com/stellar/stellar-docs/pull/733
