### ISSUE TITLE
soroban-cli: add update check

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-cli#1162]
### What problem does your feature solve?

People install soroban-cli and then don't upgrade until a problem is encountered.

For example: https://discord.com/channels/897514728459468821/966788672164855829/1194759622339342588

### What would you like to see?

The CLI checking if a new version is available and informing the user they could update to it.

**Comment by willemneal** [comment]
Sure! Go for it! It's low priority at the moment.
