### ISSUE TITLE
soroban-cli: Document JSON schema 

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-cli#1179]
For CLI documentation, please provide a detailed explanation documenting JSON schema and how that relates to the CLI

- [x] Canonical XDR JSON (rs-stellar-xdr)

**Comment by leighmcculloch** [comment]
Once we have implemented the generation of json schema from the rust xdr libs in:
- https://github.com/stellar/rs-stellar-xdr/issues/348

What's the plan for how to use the json schema to document the format? Is the goal to simply point people at the json schema json file(s) or to use it to generate some docs for the soroban/stellar docs?

**Comment by janewang** [comment]
We discussed a couple of different places to enable a JSON schema>  
- Document this JSON schema is helpful to developer on the documentation
- We could also think about places in Lab where we allow the users to optional enable JSON as the format
- There are some thinking on RPC to enable JSON to be requested on the fly

**Comment by janewang** [comment]
The JSON schema requires a documentation.

**Comment by janewang** [comment]
JSON requires more comments. Generated docs will most likely not have comments available. 

[ ] Generate docs / could try to generate us markdown and migrate to dev docs
[ ] Add comments to generated docs
[ ] Surface generated docs in dev docs
