### ISSUE TITLE
TS Bindings on Windows returns 'program not found' error

### ISSUE THREAD

**Issue by Row-Bear** [stellar/stellar-cli#1214]
### What version are you using?

20.3.1

### What did you do?

On a Windows machine, ran `soroban contract bindings typescript --network testnet --contract-id $(cat .soroban/contract_id) --output-dir node_modules/soroban-contract-client`

### What did you expect to see?
Some form of Succes!

### What did you see instead?
error: program not found

Some observations and guesses from my side:
Files are actually created in node_modules/soroban-contract-client, including index.ts which has the correct interfaces for my contract.
I suspect/guess the error originates in this [line](https://github.com/stellar/soroban-cli/blob/ae5446f63ca8a275e61912019199254d598f3bd5/cmd/soroban-cli/src/commands/contract/bindings/typescript.rs#L116) but I may be wildly off.
npm is installed

**Comment by leighmcculloch** [comment]
This is an ongoing issue plaguing windows users:
- https://discord.com/channels/897514728459468821/966788672164855829/1302894462321557525

**Comment by leighmcculloch** [comment]
Rather than fixing the issue of calling out to npm. Could we remove the dependency on npm? Other tools that generate npm packages, like `wasm-bindgen`, don't call out to npm afaict.

**Comment by Ifropc** [comment]
This issue is no longer relevant: running npm was removed in #1731 so it should no longer be an issue.
Please feel free to open a new issue if there's any problem with bindings on win
