### ISSUE TITLE
Support key protection

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-cli#1255]
The CLI is a development tool but is also used for interacting with contracts on networks as part of developer administation, such as deploying contracts and initializing them.

The CLI could do a few things to improve the protection of keys that are used in mainnet/pubnet.

For keys used only for dev and testing, key protection features are likely to be a hinderance and not useful, so this issue is not a suggestion to require key protection, just that it be available.

I've placed some ideas below. If anyone has other ideas for how the CLI could help a user protect their key, please post suggestions in comments, and I'll aggregate suggestions into the issue description.

```[tasklist]
### Ideas
- [ ] Support encrypting keys with a passphrase.
- [ ] Support storing keys in system keychains (OS specific).
- [x] Support using keys in hardware wallets. #1178
```

**Comment by janewang** [comment]
Closing this ticket for now, as we have support for hardware wallet.
