### ISSUE TITLE
can't install v20.3.4 on Sonoma 14.4.1

### ISSUE THREAD

**Issue by aristidesstaffieri** [stellar/stellar-cli#1308]
### What version are you using?
20.3.4

### What did you do?
`cargo install --locked soroban-cli --features opt`

### What did you expect to see?
successful install

### What did you see instead?
```
failed to run custom build command for `openssl-sys v0.9.90

... truncated ...

  --- stderr
  make: *** read jobs pipe: Resource temporarily unavailable.  Stop.
  make: *** Waiting for unfinished jobs....
  thread 'main' panicked at /Users/aristidesstaffieri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-111.28.1+1.1.1w/src/lib.rs:506:13:



  Error building OpenSSL:
      Command: cd "/var/folders/wp/0dgpg2yx2c7cz5nrvlw6j6sc0000gn/T/cargo-installukLigy/release/build/openssl-sys-f839c01b257f2bbc/out/openssl-build/build/src" && MAKEFLAGS="-j --jobserver-fds=12,15 --jobserver-auth=12,15" "make" "build_libs"
      Exit status: exit status: 2
```

OpenSSL for me installed with homebrew and is at the homebrew path but another user has hit this with an openSSL install at the system path also. 
Related Discord thread - https://discord.com/channels/897514728459468821/1234885504017895476

**Comment by willemneal** [comment]
You can install cargo-binstall and then install using a pre-built binary:
To install `cargo-binstall`
```
curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
```

```
cargo binstall -y soroban-cli
```
Much faster and better for CI.

**Comment by gangov** [comment]
thanks @willemneal that worked for me as well

**Comment by willemneal** [comment]
@gangov You're correct it won't be the most current release, but `opt` should be included when the release binaries are built! I'll look into that.

**Comment by gangov** [comment]
thanks for looking into it. This is the message I get at the end when I try to deploy with the soroban cli:

```Rust
Contracts compiled.
Optimize contracts...
error: Must install with "opt" feature, e.g. `cargo install --locked soroban-cli --features opt
```

**Comment by janewang** [comment]
You need to install the cli with `--feature opt`.  Closing this bug.
