### ISSUE TITLE
[Critical] Build-only and Sim-only should output TransactionEnvelope

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-cli#1322]
### What version are you using?

199a88a0be72c4caaef59c1e918e199e4e247078

### What did you do?

Ran a command with the `--build-only` option.

### What did you expect to see?

A transaction envelope to be outputted.

### What did you see instead?

A transaction outputted, incompatible with other tools.

For example:

<img width="607" alt="Screenshot 2024-05-10 at 12 37 24 pm" src="https://github.com/stellar/soroban-cli/assets/351529/09621e48-1487-4774-afd3-f01f3dca8d6a">

### Discussion

Tools should always output, and accept as input, full envelopes because otherwise other tools that the inputs/outputs are used with won’t know what type of transaction we’ve given them.

It’s a bit confusing because tools always use the term ‘transaction’ to talk about what they accept as input, but in reality when tools like the Lab and others say they accept or build a transaction, they actually mean a transaction envelope.

**Comment by willemneal** [comment]
This is fixed.
