### ISSUE TITLE
Proxy problem about CLI configuration

### ISSUE THREAD

**Issue by JiamingSuper** [stellar/stellar-cli#1324]
soroban-cli How to configure the proxy?

When I use the 'soroban contract deploy' command to deploy contracts on the test network, I keep getting an error message: error: jsonrpc error: Request timeout

I here by https://developers.stellar.org/docs/smart-contracts/getting-started/setup tutorial step by step operation, when preparing accounts, The account was created successfully but the fund address failed, indicating that the request timed out

I tried to configure the proxy on the terminal: export https_proxy....... But it didn't seem to work

**Comment by willemneal** [comment]
What version are you using? `soroban version` (soon to be `stellar version`.

**Comment by janewang** [comment]
I think this is related to RPC issue, unfortunately. I'm closing the issue as the response is from https://github.com/stellar/soroban-rpc
