### ISSUE TITLE
error: xdr processing error: xdr value invalid | Bug Report

### ISSUE THREAD

**Issue by Stellar-tickets** [stellar/stellar-cli#1331]
as reported here in discord: https://discord.com/channels/897514728459468821/966788672164855829/1240783985370595429

you can't invoke hello world from 20.3.4 on testnet
maybe we need to use v21 for p21?
Hey guys I'm p[robably doing something wrong.
I deploy it, it returns the contract key, but I can't invoke

soroban contract deploy \
        --wasm target/wasm32-unknown-unknown/release/hello_world.wasm \
        --source bob \
        --network testnet
CA2PGFVXARVLBJHITPJLCMTKL2VNO32HYUES5RJRT3CHK35IOFDPG2S6
soroban-hello-world soroban contract invoke \
  --id CA2PGFVXARVLBJHITPJLCMTKL2VNO32HYUES5RJRT3CHK35IOFDPG2S6 \
  --source bob \
  --network testnet \
  -- \
  hello \
  --to RPC
error: xdr processing error: xdr value invalid

**Comment by Stellar-tickets** [comment]
🔗 [Discuss this issue on Discord](https://discord.com/channels/897514728459468821/1240825503280267285)

**Comment by willemneal** [comment]
I can confirm that I was able to invoke with `soroban 21.0.0-preview.1`, so my guess is that the XDR was updated and now the old version doesn't work.  Though I thought it was supposed to be backward compatible @leighmcculloch
