### ISSUE TITLE
 CLI Installation Issue

### ISSUE THREAD

**Issue by SarthiBorkar** [stellar/stellar-cli#1336]
### What did you do?
I m a student and a solidity dev learning and starting to build on steller so i was installing CLI soroban
PS C:\Users\admin> cargo install --locked soroban-cli
    Updating crates.io index
  Installing soroban-cli v20.3.4
    Updating crates.io index
    Updating crates.io index
   Compiling proc-macro2 v1.0.69
   Compiling unicode-ident v1.0.12
   Compiling serde v1.0.192
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling thiserror v1.0.55
error: linker `link.exe` not found
  |
  = note: program not found

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that Visual Studio 2017 or later, or Build Tools for Visual Studio were installed with the Visual C++ option.

note: VS Code is a different product, and is not sufficient.

error: could not compile `serde` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `proc-macro2` (build script) due to 1 previous error
error: could not compile `thiserror` (build script) due to 1 previous error
error: failed to compile `soroban-cli v20.3.4`, intermediate artifacts can be found at `C:\Users\admin\AppData\Local\Temp\cargo-installK1pooJ`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

### What did you expect to see?
when i typed soroban it give error : 
PS C:\Users\admin> soroban
soroban : The term 'soroban' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the     
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ soroban
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (soroban:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

### What did you see instead?
i an mentioned above

**Comment by willemneal** [comment]
@fnando This seems like an issue for you. 

What I would suggest is using [cargo-binstall](https://github.com/cargo-bins/cargo-binstall) as there are already prebuilt windows binaries released on github.

**Comment by SarthiBorkar** [comment]
Will do that. Thank you
