### ISSUE TITLE
error TS2304: Cannot find name 'Context'.

### ISSUE THREAD

**Issue by kalepail** [stellar/stellar-cli#1344]
### What version are you using?

```
% soroban version
stellar 21.0.0-rc.1 (8c17d747c95ad6e7fd649053c9516fa4067ae509)
soroban-env 21.0.1 (f2b734b6360ae04ba730307be3988619dd0f59a3)
soroban-env interface version 90194313216
stellar-xdr 21.0.1 (da0cbc6f75eaf03423810b8e9d730a03dfa8517e)
xdr curr (1a04392432dacc0092caaeae22a600ea1af3c6a5)
```

### What did you do?

```
soroban contract bindings typescript --output-dir ./passkey-kit-sdk --id CAON467XAJ6DXEC7CYVQUZBGRSGA23LBTNOD4VLOHERRCW5UIN356IIH --wasm contracts/out/webauthn_account_secp256r1.optimized.wasm --network testnet
```

To reproduce clone https://github.com/kalepail/superpeach and run the above command after running `make build` in the `./contracts` directory.

### What did you expect to see?

Success.

### What did you see instead?

```
added 29 packages, and audited 30 packages in 7s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New patch version of npm available! 10.8.0 -> 10.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.1
npm notice To update run: npm install -g npm@10.8.1
npm notice

> passkey-kit-sdk@0.0.0 build
> tsc

src/index.ts:163:136 - error TS2304: Cannot find name 'Context'.

163   __check_auth: ({signature_payload, signature, auth_contexts}: {signature_payload: Buffer, signature: Signature, auth_contexts: Array<Context>}, options?: {
                                                                                                                                           ~~~~~~~

src/index.ts:163:136 - error TS4078: Parameter '{signature_payload, signature, auth_contexts}' of exported function has or is using private name 'Context'.

163   __check_auth: ({signature_payload, signature, auth_contexts}: {signature_payload: Buffer, signature: Signature, auth_contexts: Array<Context>}, options?: {
                                                                                                                                           ~~~~~~~

Found 2 errors in the same file, starting at: src/index.ts:163
```

**Comment by kalepail** [comment]
Arguably the TS bindings shouldn't expose the `__check_auth` function as it's not callable externally

**Comment by leighmcculloch** [comment]
Agreed we shouldn't generate bindings for the check auth fn. that should be a small change.

**Comment by leighmcculloch** [comment]
From best I can tell the generated bindings don't contain the `__check_auth` function. Maybe it is getting added by the `ContractClient` in the js-stellar-sdk? cc @chadoh

**Comment by chadoh** [comment]
Will `soroban::sdk::auth::Context` ever be used in public methods? If so, then we should also add an equivalent TS type for the bindings to use. Which would also fix this problem.

**Comment by leighmcculloch** [comment]
> We _could_ try to modify that logic to exclude private methods, but to me the real bug seems like the fact that `soroban-sdk` is including private methods in the XDR spec!

The method is a public method, trait impl fn's don't have `pub` on the front, but they are public. A bit of a personal gripe for me personally on this! It's confusing, trips me up a lot too.

That said, there could be an argument for excluding `__check_auth` from the spec, but I think it is necessary so that tooling knows the function is there, and so that tooling that needs to generate contract traits / interfaces keep it included so that if you are implementing a trait for a contract you end up with the same surface area implemented.

All clients should probably not generate invoking functions for methods beginning with `__` given that the host doesn't allow invoking them directly:

https://github.com/stellar/rs-soroban-env/blob/8ee24193a890173b3bedd72480f28ceafd18c4fa/soroban-env-host/src/host/frame.rs#L34-L37

**Comment by chadoh** [comment]
Ohhhh, very helpful, thanks @leighmcculloch! I think we can easily exclude functions prefixed with `__` from the functions added to the `interface Client` in the TS bindings. We'd probably just want a `filter` on the `fns` right after this logic we'd probably want a filter on fns after this line? https://github.com/AhaLabs/soroban-cli/blob/44b0f36b01f3a5f761410632f428ac69969e5fad/cmd/crates/soroban-spec-typescript/src/lib.rs#L99-L101

**Comment by willemneal** [comment]
You'd also need to update the JS as the function will be there even if the types don't show them.
