### ISSUE TITLE
Binding generated errors don't include the error name in their generated message

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-cli#1346]
### What version are you using?

bc3031e7c2609d7e57ef6f3d8a482091cc0e1eab

```
$ stellar version
stellar 21.0.0-rc.1 (bc3031e7c2609d7e57ef6f3d8a482091cc0e1eab)
soroban-env 21.0.1 (f2b734b6360ae04ba730307be3988619dd0f59a3)
soroban-env interface version 90194313216
stellar-xdr 21.0.1 (da0cbc6f75eaf03423810b8e9d730a03dfa8517e)
xdr curr (1a04392432dacc0092caaeae22a600ea1af3c6a5)
```
### What did you do?

```
$ export SOROBAN_NETWORK=testnet
$ stellar contract bindings typescript \
    --id CAON467XAJ6DXEC7CYVQUZBGRSGA23LBTNOD4VLOHERRCW5UIN356IIH \
    --output-dir ./passkey-kit-sdk
```

### What did you expect to see?

Bindings generated with meaningful errrors.

The contract has names on its errors, as evidenced by:

```console
$ stellar contract fetch --id CAON467XAJ6DXEC7CYVQUZBGRSGA23LBTNOD4VLOHERRCW5UIN356IIH > passkey-kit-sdk.wasm
$ wasm-cs passkey-kit-sdk.wasm read contractspecv0 -f binary | stellar-xdr d --type ScSpecEntry --input stream |  jq -s '.[0]'
{
  "udt_error_enum_v0": {
    "doc": "",
    "lib": "",
    "name": "Error",
    "cases": [
      {
        "doc": "",
        "name": "NotInited",
        "value": 1
      },
      {
        "doc": "",
        "name": "AlreadyInited",
        "value": 2
      }
    ]
  }
}
```

### What did you see instead?

```
$ cat ./passkey-kit-sdk/dist/index.js
...
export const Errors = {
    1: { message: "" },
    2: { message: "" }
};
...
```

### Notes

The wasm at the time of execution had hash `50f77f1edcfdca4bd275530b48f2e55d6c34fcc39111bc866c5a93feb384225d`.

**Comment by willemneal** [comment]
Damn it used it! But it was a very fragile solution based on regex if I remember correctly. @chadoh This might be a good issue for @BlaineHeffron, however, we should probably transfer this to the `js-soroban-sdk` correct?

**Comment by chadoh** [comment]
I agree, this seems like a good one for @BlaineHeffron, and I asked him in Discord and he is game to try it.

@BlaineHeffron the current `Errors` const is constructed [in soroban-spec-typescript/lib.rs#entry_to_method_type](https://github.com/AhaLabs/soroban-cli/blob/44b0f36b01f3a5f761410632f428ac69969e5fad/cmd/crates/soroban-spec-typescript/src/lib.rs#L239-L249). Meanwhile, `errorTypes` is constructed dynamically when you initialize a contract client over [in stellar-sdk](https://github.com/stellar/js-stellar-sdk/blob/1b6d7aae238e6f294b1b09f141ff20e07be74325/src/contract/client.ts#L34-L40). Honestly, I'm not sure this `Errors` const is even being used anymore! If you look into it and find out it's not, then this will be a really easy "bug" to fix 😄

**Comment by BlaineHeffron** [comment]
It was using "doc" instead of "name" for the message:

It was outputting this:
```
export const Errors = {
  1: {message:""},
  2: {message:""},
  3: {message:""},
  4: {message:""},
  5: {message:""},
  6: {message:""},
  7: {message:""},
  8: {message:""},
  9: {message:""},
  10: {message:""}
}```

Now it outputs this:

```
export const Errors = {
  1: {message:"NotFound"},
  2: {message:"NotPermitted"},
  3: {message:"ClientDataJsonChallengeIncorrect"},
  4: {message:"Secp256r1PublicKeyParse"},
  5: {message:"Secp256r1SignatureParse"},
  6: {message:"Secp256r1VerifyFailed"},
  7: {message:"JsonParseError"},
  8: {message:"InvalidContext"},
  9: {message:"AlreadyInited"},
  10: {message:"NotInited"}
}
```

Is that what we want?

**Comment by willemneal** [comment]
Ideally there could be a doc string `/// Blank was not found...` which could provide even more context for the error. But I think that descriptive names should be good enough.

**Comment by BlaineHeffron** [comment]
Currently it will take the docstring above the enum declaration e.g 

```

/**
 * Represents the different kinds of errors that can occur in the application.
 */
export const Errors = {
  1: {message:"NotFound"},
  2: {message:"NotPermitted"},
  3: {message:"ClientDataJsonChallengeIncorrect"},
  4: {message:"JsonParseError"},
  5: {message:"InvalidContext"},
  6: {message:"AlreadyInited"},
  7: {message:"NotInited"}
}
```

But it doesnt grab the docstrings above each enum:

```
/// Represents the different kinds of errors that can occur in the application.
pub enum Error {
    /// The requested item was not found.
    NotFound = 1,
    
    /// The operation was not permitted.
    NotPermitted = 2,
```

**Comment by willemneal** [comment]
Ah then it needs to be implemented by the soroban-sdk, so lets just stick with the enum names.

**Comment by BlaineHeffron** [comment]
My mistake, each enum element does have a doc property. I added some logic to throw them in there if they exist. I'll open a PR

**Comment by BlaineHeffron** [comment]
https://github.com/stellar/stellar-cli/pull/1364
