### ISSUE TITLE
`network container start`: automatically run `network add` 

### ISSUE THREAD

**Issue by chadoh** [stellar/stellar-cli#1410]
When I `stellar network container start local` and then `stellar network ls`, I should see the network I just started.

Right now I need to dig through `stellar network container logs local` to find the passphrase and I think I just need to know the URL.

**Comment by chadoh** [comment]
@elizabethengelman as part of https://github.com/stellar/stellar-cli/pull/1408, I'm adding a default `--network local`. Do you think that's a good-enough way to solve this issue?

**Comment by elizabethengelman** [comment]
@chadoh Yeah, that seems like it should solve this issue! 👍
