### ISSUE TITLE
Add `--overwrite` to `stellar contract init`

### ISSUE THREAD

**Issue by fnando** [stellar/stellar-cli#1425]
### What problem does your feature solve?

Templates change. Maybe you want to pull in all new changes, especially when using astro templates.

### What would you like to see?

`--overwrite` can overwrite all files automatically.

### What alternatives are there?

Removing files manually then running the command to install a new version of the templates.

**Comment by leighmcculloch** [comment]
This option would make the init command very destructive. The user already has tools they can use to destroy files, so the cli wouldn't be providing something significant impactful. 

Also I expect a command for overwriting will be more useful to someone repeatedly starting from scratch which doesn't exactly sound like the workflow of a contract developer. It sounds like the workflow of someone testing the CLI. 

What's the motivation behind adding the option?
