### ISSUE TITLE
Enable the CLI to generate links or files compatible with the Stellar Lab

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-cli#1428]
## What problem does your feature solve?
To transactions created in the CLI, allow users to connect to a wallet not stored by the CLI. This is being explicitly asked by developer

## What would you like to see?
- Use Wallet kit (https://github.com/Creit-Tech/Stellar-Wallets-Kit) - Wallet kit is already implemented in Lab
- Land user in [Lab](https://beta-laboratory.stellar.org/?$=network$id=testnet&label=Testnet&horizonUrl=https:////horizon-testnet.stellar.org&rpcUrl=https:////soroban-testnet.stellar.org&passphrase=Test%20SDF%20Network%20/;%20September%202015;;) with wallet kit open 
- Note: Lab will use https://lab.stellar.org as the URL when launched

This issue includes pass the xdr to the sign page on Lab and pass back the signed xdr to the CLI.

**Comment by elizabethengelman** [comment]
@janewang @Ifropc as I'm working on this, I found this ticket too https://github.com/stellar/stellar-cli/issues/674 - how is #674 different from this ticket (#1428)?

**Comment by janewang** [comment]
@elizabethengelman Thank you for picking up the ticket. I closed the other one. There is only one ticket for this Objective and you are assigned to it :)

**Comment by Ifropc** [comment]
From my understanding #674 is a part of this ticket

**Comment by elizabethengelman** [comment]
Cool, thanks for the clarification!
