### ISSUE TITLE
Enable transaction creation for critical classic commands

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-cli#1437]
### What problem does your feature solve?
Support some classic functionalities on the CLI

- [x] Create account 
- [x] Payment
- [x] Set options
- [x] Bump sequence
- [x] Account Merge
- [x] Manage data
- [x] InvokeFunction 
- [x] Extend footprint ttl 
- [x] Restore footprint 
- [] ~Allow trust~ Deprecated in favor of Set Trustline Flags
- [x] Change trust
- [x] Set trustline flags

The following will be added once we can have multiple operations:
- Begin sponsoring future reserves
- End sponsoring future reserves

Operations: https://developers.stellar.org/docs/learn/fundamentals/transactions/list-of-operations

**Comment by leighmcculloch** [comment]
> Enable transaction submission for critical classic commands

Is the goal of this command to support submitting the transaction or creating the transaction?

**Comment by leighmcculloch** [comment]
Sounds like a cool feature. It competes with the planned stc-like functionality that is described in the following issues. Given the significant amount of effort both are we should probably prioritize one and decide if we want two ways to do something or one.

- https://github.com/stellar/stellar-cli/issues/1180
- https://github.com/stellar/stellar-cli/issues/1290

Or, will `tx create-account` kick off an stc-like session with a tx template prebuilt with a create-account op?

Do we have any plans for what these commands will look like?

**Comment by leighmcculloch** [comment]
Or maybe tx create-account would only kick off an stc-like session if not all options were provided? Or is the goal for this command to be used in scripting in which case we wouldn't want an stc-like session?

**Comment by janewang** [comment]
@leighmcculloch Sorry about that. I updated the ticket title but forgot to do the same in the Epic. It's now updated: https://github.com/stellar/stellar-cli/issues/1180

Here's from the latest discussions: https://docs.google.com/document/d/1MHjQ-R6Dh_Ykhq5VcOT-d1-z5yoNrPC5RjNA0MEmEno/edit#bookmark=id.1uhcuw5mej48

The edit experience should be able to support multiple operations. Format for editing under consideration: JSON, JSON 5, TOML. We can use `–build-only` flag to check if the file builds. For non-valid JSON / TOML, we could add comment to indicate there is an error.

**Comment by janewang** [comment]
@willemneal and @fnando please assign yourself to the ones you want to to tackle
