### ISSUE TITLE
Update testcontainers dep to use crate.io dep instead of a specific git sha

### ISSUE THREAD

**Issue by elizabethengelman** [stellar/stellar-cli#1471]
We're using `testcontainers` for the ledger emulator tests, and have some dependency mismatches that prevented us from using a tagged release. 

- for `testcontainers` 0.16.0 we have a dependency mismatch with the version of the `quote` crate: testcontainers requires the quote crate at version ^1.0.35, but soroban-env-host is using 1.0.33
- for previous testcontainers releases, there are mismatches between more recent versions of bollard-stubs (need to do some more investigation to remember exactly what the issue was)

Solution ideas:
- loosen requirements for `quote` in soroban-env-host and try `testcontainers` 0.16.0 (or even 0.17.0)

**Comment by leighmcculloch** [comment]
+1 we have loosened some dependencies in env recently and could do same with quote I think.
