### ISSUE TITLE
Expand the list of frontend template options

### ISSUE THREAD

**Issue by fyodorio** [stellar/stellar-cli#1476]
### What problem does your feature solve?
`contract init` command (https://developers.stellar.org/docs/tools/stellar-cli#stellar-contract-init) provides a flag (`--frontend-template`) allowing to generate UI code for contracts _via a repository_ (if I'm not mistaken). But there's only one [publically-available/searchable] template now (https://github.com/stellar/soroban-astro-template) and no specific pointers on where to find other options, or how to create them (minimal requirements for such a repo?)

### What would you like to see?
Other options/examples for UI generation, or short documentation on how to create one (for instance, with Preact, Svelte, Vue, or whatnot)

### What alternatives are there?
Manual creation? Which probably requires a lot more stuff to take care of...

**Comment by janewang** [comment]
Please document how to best to contribute to add more frontend templates, and we could pass over  devrel.

**Comment by fyodorio** [comment]
@janewang is it a request to the reporter or to the assignee? 😅 (_I mean, I could, but maybe I'm not the most competent champion for that here yet_)

**Comment by janewang** [comment]
This is a request for the assignee @chadoh

**Comment by janewang** [comment]
@chadoh Were you able to add a how-to contribute doc as the the first step as you offered on the call 2 week ago? Subsequently, as discussed we are planning to find community contributors.

**Comment by chadoh** [comment]
I believe this document, [Develop contract initialization templates](https://developers.stellar.org/docs/build/guides/dapps/soroban-contract-init-template), is probably most of what we need. I'll go through it and make sure it has what was in my head, as a foundation for creating a community initiative around getting new templates.

**Comment by fyodorio** [comment]
This a really good thorough doc, I wish I knew about that earlier 👍 What I did basically is just used an arbitrary frontend repo as a template with soroban init, and then augmented it with the stuff from the existing Astro template 😅 This doc explains everything of that in a detailed way, kudos!

What would help too is probably to underpin more explicitly that you can use _any_ existing repo as a basis actually, and highlight what are the integral parts of a soroban template after that (the init script, the packages, and all that jazz). Also, some starters use shell scripts instead of Node scripts, and that's totally legit too, I would also describe shortly what you need to include in an initialization script in general, in language-agnostic way.

Sorry for the unsolicited two cents, feel free to ignore if that's irrelevant 😅

**Comment by janewang** [comment]
Closing this issue and can discuss with dev rel
