### ISSUE TITLE
feat: config as own crate

### ISSUE THREAD

**Issue by willemneal** [stellar/stellar-cli#1489]
What I'm imagining is using an alias when importing a contract: 

```rust
import_contract!(hello_world);
```
Then you would need to use an env variable to set the network so that it could look up the alias. You could also do the same for keys, but this one would make it a much better experience and make the `hello_world`  module feel like a real rust import.

> Feels right to move logic like the shared args out of the network commands module into a shared place due to the common nature and the args not being scoped to the network command.
> 
> The refactor looks good to me in that context 👏🏻 .
> 
> > This separates it out so that we can begin the process of pulling it out into it's own crate.
> 
> That being said, the refactor groups cli code together, but doesn't separate out config parsing/writing logic from tightly coupled cli logic, so I'm not sure this change sufficiently prepares a module for extraction to another crate.
> 
> > This should become it's own crate to allow devs to use accounts and aliases when compiling contract.
> 
> Could you share more about this workflow? I wouldn't expect compiling contracts to embed aliases or account data into contracts, and even if the cli needed to do that the cli can already access them.
> 
> I am probably missing a critical part of how this will serve folks, but moving config into a separate crate seems very low impact / priority at the moment. What am I missing?

_Originally posted by @leighmcculloch in https://github.com/stellar/stellar-cli/pull/1479#pullrequestreview-2200072839_

**Comment by leighmcculloch** [comment]
> ```rust
> import_contract!(hello_world);
> ```

Early on there was an issue open for something like this:
- https://github.com/stellar/rs-soroban-sdk/issues/728

However, once contract upgradability was added, the contract ID no longer points to a consistent code file which would make reproducibility challenging. Reproducible builds is something being pursued, see [this Discord thread for the latest on that](https://discord.com/channels/897514728459468821/1230143202506313738).

Another issue with importing contracts from an alias is that it assumes the alias is part of the project that gets shared, but the local .soroban directory is git-ignored, and a user might have the alias stored outside the project either in a parent directory or in the global config.

To explore auto-downloading the contract it'd probably need to accept a network passphrase (or name) and the wasm hash. It's relatively easy for folks to figure out what the wasm hash is from an explorer.

**Comment by willemneal** [comment]
I guess for me I'm interested in using it for our [loam](github.com/loambuild/loam) which has a contract and wasm-hash registry. I have had this working for my previous project smartdeploy. But that used it's own alias system. But what was nice is you could do `smartdeploy install hello_world` and it would add it to your local target directory, and I had the plan of adding it to the `Cargo.toml`. Loam now has an `environment.toml` which will be where the contracts aliases to be installed will be.

Anyway we can copy the code that is required, but we wanted `loam_sdk` to not depend on the CLI to get access to the config.

As for the issue with the CLI args being intertwined. I agree it's an issue, but it's also useful for those that would want to make their own CLI with access to the config logic. The solution to still using it in an sdk to to hide the clap parts behind a feature.

So the really the question is do we want to provide the config as a separate tool? Would there be users beside loam that would be interested?

**Comment by leighmcculloch** [comment]
I understand the motivation in reducing code duplication across CLIs that'll have similar uses and similar UIs using the CLI config benefiting from sharing the clap setup, but areas of code we've used that same pattern with between the stellar-rpc-client and the cli have made it difficult to maintain the CLI so I think we need to keep the CLI presentation layer within the CLI.

**Comment by janewang** [comment]
Could we close this ticket? Is this important for Q3?

**Comment by leighmcculloch** [comment]
It's not critical for the cli and without getting the boundary right I think this issue risks reducing the maintainability of the cli. So I suggest we close and not focus on it in the near future.
