### ISSUE TITLE
markdown bug: network args are not separated

### ISSUE THREAD

**Issue by willemneal** [stellar/stellar-cli#1504]
Why aren't the options for the network under a separate section like on other commands?

_Originally posted by @leighmcculloch in https://github.com/stellar/stellar-cli/pull/1406#discussion_r1689091741_
        
Turns out this applies to all network args in the markdown.

Not sure how important this is, but it would be good if the `--help` output matched the markdown.

**Comment by leighmcculloch** [comment]
Ahh, I had thought you were doing something different for that specific command. If it's a shortcoming of the markdown gen I don't think we need to worry about it too much. We could open an issue on the respective crate's repo otherwise we probably don't need to burn any cycles on this.

**Comment by janewang** [comment]
Not impactful enough change

**Comment by leighmcculloch** [comment]
We could open an issue on the markdown crate that we use to generate the help.
