### ISSUE TITLE
Auto-parsable textual representation of contract inspect (Yaml or Json)

### ISSUE THREAD

**Issue by OlegJakushkin** [stellar/stellar-cli#1507]
### What problem does your feature solve?
Automatically parse results of `contract inspect`. Currently when I do
`C:\Users\olegj\.cargo\bin\stellar.exe contract inspect --wasm .\token_stellar.wasm --output docs > out.txt `
I see
```
Env Meta: AAAAAAAAAAAAAAAd
 ÔÇó Interface Version: 29 (protocol: 0, interface: 29)

Contract Meta: None

Contract Spec:
 ÔÇó Error: TokenError
     Cases:
      ÔÇó ScSpecUdtErrorEnumCaseV0 {
            doc: StringM(),
            name: StringM(InternalError),
            value: 1,
        }
      ÔÇó ScSpecUdtErrorEnumCaseV0 {
            doc: StringM(),
            name: StringM(AlreadyInitializedError),
            value: 3,
        }
```
While if I print it onto console I see
```
Env Meta: AAAAAAAAAAAAAAAd
 • Interface Version: 29 (protocol: 0, interface: 29)

Contract Meta: None

Contract Spec:
 • Error: TokenError
     Cases:
      • ScSpecUdtErrorEnumCaseV0 {
            doc: StringM(),
            name: StringM(InternalError),
            value: 1,
        }
      • ScSpecUdtErrorEnumCaseV0 {
            doc: StringM(),
            name: StringM(AlreadyInitializedError),
            value: 3,
        }
```
It is hard to automatically parse (doable yet sucks a bit from Python). 

### What would you like to see?
YAML (or JSON, e.g. draft-07 like Sei and Ethereum RPC does for typed formatted textual representations) human readable, automatically parsable docs. Something like `C:\Users\olegj\.cargo\bin\stellar.exe contract inspect --wasm .\token_stellar.wasm --output yaml > out.yaml` - it would even look similar to current `docs` output.

### What alternatives are there?
Parsing `xdr-base64` and `xdr-base64-array`  is hard from my Python code.

**Comment by leighmcculloch** [comment]
Hi @OlegJakushkin, thanks for opening this issue. The inspect command isn't designed for parsing, the format can change at anytime, as it is only intended for human interaction.

@Ifropc is proposing a new command earlier today that is very similar to what you're hoping to use inspect for:
- #1506 

I suggest we close this issue and collaborate on #1506.

**Comment by OlegJakushkin** [comment]
Thank you @leighmcculloch , [ #1506 ](https://github.com/stellar/stellar-cli/issues/1506)would do it for me=)
Just for my understanding - what humans understand xdr-base64?=)
