### ISSUE TITLE
TS Bindings: check if has NPM, throw useful error + instructions, and fix broken links to old soroban docs

### ISSUE THREAD

**Issue by chadoh** [stellar/stellar-cli#1511]
Reported by a user:

> After running `bindings typescript` it returns an error, "program not found". And while it does generate some typescript files, the node modules folder as well as the dish folder is missing.

This happens because right now we assume that you have Node/NPM, rather than verifying and erroring with a more useful error message.

Let's check if Node & NPM are installed and, if not, error with this explanation:

> This command generates an NPM package for use with a NodeJS codebase. You need Node/NPM to build the generated package, and you'll also need it to import and use it. There are many ways to install Node; a popular way is nvm, Node Version Manager: https://github.com/nvm-sh/nvm

**Comment by leighmcculloch** [comment]
Suggested tweaks to the explanation:

> This command generates an NPM package for use with a NodeJS codebase. Node/NPM is required to build the generated package, import it, and use it. See https://nodejs.org/en/download to install Node/NPM.

**Comment by janewang** [comment]
For cleaning up and add checks and errors, could we also clean up the old links to soroban-docs. We have merged all docs under stellar docs.

**Comment by janewang** [comment]
we are not going to use npm anymore, closing

**Comment by leighmcculloch** [comment]
This was closed in favor of:
- https://github.com/stellar/stellar-cli/issues/1512
