### ISSUE TITLE
contract extend doesnt work with --wasm or --wasm-hash

### ISSUE THREAD

**Issue by BlaineHeffron** [stellar/stellar-cli#1557]
### What version are you using?
```
stellar 21.4.0 (v20.0.0-267-gb92725bdc3543c8796f5ebd4444ec277a175de05)
soroban-env 21.2.0 (8809852dcf8489f99407a5ceac12625ee3d14693)
soroban-env interface version 90194313216
stellar-xdr 21.2.0 (9bea881f2057e412fdbb98875841626bf77b4b88)
xdr curr (70180d5e8d9caee9e8645ed8a38c36a8cf403cd9)
```

### What did you do?

I ran the command in the guide on extending contracts via their wasm or wasm hash: 

```
stellar contract extend \
    --source S... \
    --network testnet \
    --wasm ../relative/path/to/soroban_contract.wasm \
    --ledgers-to-extend 535679 \
    --durability persistent
```

### What did you expect to see?

success

### What did you see instead?

```
stderr=```
thread \'main\' panicked at cmd/soroban-cli/src/commands/contract/extend.rs:134:43:
called `Option::unwrap()` on a `None` value
```

It panics when it doesn't find the `--id` argument. The issue is that extend seems to be written only to use a contract ID to find the contract. But it accepts the flattened `key` arguments which allows  a wasm, wasm-hash or contract-id. So to fix the issue it needs to check for the presence of any and perform the proper ledger fetching logic depending on the one given. Or its argument list should only include a contract-id and not the wasm, wasm-hash option (and we will need to remove those guide entries). I'm not sure which is the intended behavior is but I'm assuming its the former given that there are guide entries indicating you can extend via wasm or wasm-hash: https://developers.stellar.org/docs/build/guides/cli/extend-contract-wasm

**Comment by janewang** [comment]
@BlaineHeffron To my knowledge, we can extend the contract's wasm code, the contract instance itself, and the ledger entries on the contract. So it probably shouldn't require a contract id always. 

 https://developers.stellar.org/docs/build/guides/cli/extend-contract-instance
