### ISSUE TITLE
warn emoji looks sad

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-cli#1576]
### What version are you using?

main

### What did you do?

<img width="429" alt="Screenshot 2024-08-29 at 9 47 35 PM" src="https://github.com/user-attachments/assets/5ba802dd-e7b2-47f7-b18b-cef9c631f15a">

### What did you expect to see?

A warn emoji that looks like this: ⚠️ 

### What did you see instead?

A warn emoji that looks less colorful.

**Comment by leighmcculloch** [comment]
The command I'm using to triggering the warn emoji is in #1571 and not merged yet. But the warn emojis shows up elsewhere in the app, and this issue isn't dependent on #1571.

**Comment by janewang** [comment]
Leigh will check terminal font

**Comment by fnando** [comment]
Looks like this is a VScode terminal issue. The fix is to add the emoji font to the font stack. 

https://github.com/Microsoft/vscode/issues/32840

In my case, I had to actually add this:

```
"terminal.integrated.fontFamily": "'JetBrainsMonoMedium Nerd Font Mono', 'Apple Color Emoji'",
```

**Comment by leighmcculloch** [comment]
I changed my font to the following and it fixed the issue:
```
    "editor.fontFamily": "'Fira Code', 'Apple Color Emoji', monospace",
```
