### ISSUE TITLE
Use alias for network

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-cli#1610]
### What problem does your feature solve?
Simplification of the UI to use network alias everywhere

### What would you like to see?

Simplify network config on stellar-cli: drop --rpc-url and --network-passphrase and require a network alias everywhere

**Comment by fnando** [comment]
I think I can squeeze this in for the protocol 22 release. 🤞

**Comment by leighmcculloch** [comment]
> Less manual entering of passphrases

Folks can already use `--network` everywhere and they are not required to enter network passphrases, so I think the "why" needs expanding on. What's the impact of this change?

This looks like a simplification of the UI.

**Comment by fnando** [comment]
Yeah, I don't think manual entering network passphrases is the real issue. I'd say the goal it's to simplify the ui (only one way of accessing/providing network config) + codebase (flattening the network args brings more trouble than solution).
