### ISSUE TITLE
Make alias work everywhere

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-cli#1611]
### What problem does your feature solve?

[stellar-cli] make aliases work everywhere; there are a few places like snapshot create that don’t support alias (other commands too )

**Comment by fnando** [comment]
@janewang I fixed `snapshot create` on #1662. I don't really remember if other commands are still lacking support for alias. 🤔

**Comment by janewang** [comment]
Ok, closing this one, thanks @fnando
