### ISSUE TITLE
Bring colors to help message

### ISSUE THREAD

**Issue by Ifropc** [stellar/stellar-cli#1624]
### What problem does your feature solve?

Currently our help input is black and white

### What would you like to see?

It would be great to add color theme, just it's in cargo and other commands
Ref: https://github.com/clap-rs/clap/issues/3234

### What alternatives are there?

N/A

**Comment by ShantelPeters** [comment]
Please can I take this up @Ifropc

**Comment by leighmcculloch** [comment]
See:
- https://docs.rs/clap_builder/4.4.12/clap_builder/builder/styling/struct.Styles.html#example
- https://docs.rs/clap/latest/clap/struct.Command.html#method.styles

**Comment by martinvibes** [comment]
hello @Ifropc  @leighmcculloch i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor

this issue would be easy to tackle

**Comment by dev-chinx** [comment]
please @Ifropc let me work on this :)
kindly assign

**Comment by Abeeujah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
I'm a Web and Systems Software Engineer, with experience building TUI applications in  Rust, GoLang (ratatui, clap, bubbletea and termui).

### How I plan on tackling this issue
- Get the Desired color scheme to be implemented from the maintainers, preferrably included in the Xterm_256 color chart, has a AnsiColor implementation already or proceed with the current stellar brand colors.
- Create a Custom style scheme preset using the provided color scheme by the maintainers.
- Implement the preset styles by providing the styles attribute to the command interface.

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
helloi would love to work on this issue
i'm a frontend developer and blockchain dev

### How I plan on tackling this issue
please kindly assign and i'll get to work

**Comment by Abeeujah** [comment]
![Screenshot_20241001_132935](https://github.com/user-attachments/assets/a7bf665d-7271-4cd2-b2ee-dd3b785644e8)
![Screenshot_20241001_132951](https://github.com/user-attachments/assets/81f32d95-5eed-4fee-91b7-9d4a4b3b3cda)

Hi @janewang @leighmcculloch @Ifropc Please can you confirm you're satisfied with the current color theme or if there's a specified color theme you'd prefer?

**Comment by leighmcculloch** [comment]
@janewang I pushed a tweak to the PR to change the colors to match the same colours that `cargo` uses.

Two motivations for this:
- @Ifropc suggested colours like cargo in the original issue comment
- Devs often will use cargo and soroban-cli side-by-side, so the fact they look the same and have the same appearance may be helpful

Alternatively, @janewang maybe there is value in getting the design team's input, and maybe we should be using "Stellar" colors?
