### ISSUE TITLE
Consolidate HTTP client libraries to reduce complexity

### ISSUE THREAD

**Issue by overcat** [stellar/stellar-cli#1629]
### What problem does your feature solve?
Currently, the project is using multiple HTTP client libraries:
- [hyper](https://github.com/stellar/stellar-cli/blob/c8c3871ef3a409328d9b0561f87d55c00bd41071/cmd/soroban-cli/Cargo.toml#L79-L80)
- [ureq](https://github.com/stellar/stellar-cli/blob/c8c3871ef3a409328d9b0561f87d55c00bd41071/cmd/soroban-cli/Cargo.toml#L110)
- [reqwest](https://github.com/stellar/stellar-cli/blob/main/cmd/crates/stellar-ledger/Cargo.toml#L33)

This diversity of HTTP clients may lead to several issues:
- Increased complexity in the codebase
- Potential inconsistencies in how HTTP requests are handled
- Difficulties in maintaining and updating dependencies

### What would you like to see?
We should consider consolidating our HTTP client usage to a single library. This would simplify the codebase, reduce potential inconsistencies, and make maintenance easier.

### What alternatives are there?
N/A

**Comment by leighmcculloch** [comment]
Where are the different libraries being used?

**Comment by overcat** [comment]
> Where are the different libraries being used?

The following is the code in the project

ureq: https://github.com/stellar/stellar-cli/blob/c8c3871ef3a409328d9b0561f87d55c00bd41071/cmd/soroban-cli/src/commands/contract/init.rs#L22
hyper: https://github.com/stellar/stellar-cli/blob/c8c3871ef3a409328d9b0561f87d55c00bd41071/cmd/soroban-cli/src/commands/snapshot/create.rs#L413
reqwest (stellar-ledger): https://github.com/stellar/stellar-cli/blob/c8c3871ef3a409328d9b0561f87d55c00bd41071/cmd/crates/stellar-ledger/tests/utils/emulator_http_transport.rs#L7

**Comment by leighmcculloch** [comment]
Thanks.

`hyper` is also in use in the `stellar/rs-stellar-rpc-client` repo (the `jsonrpsee` http client lib uses hyper) which the cli imports.

`reqwest` also uses `hyper`.

**Comment by leighmcculloch** [comment]
If we were to make a change here, I'd suggest replacing ureq and reqwest with hyper.

**Comment by overcat** [comment]
> If we were to make a change here, I'd suggest replacing ureq and reqwest with hyper.

I saw it written on https://github.com/hyperium/hyper:
> If you are looking for a convenient HTTP client, then you may wish to consider [reqwest](https://github.com/seanmonstar/reqwest).

If there are no special reasons, using reqwest seems like a good choice. Although it relies on hyper, we won't be using hyper directly in the code.

**Comment by leighmcculloch** [comment]
That sounds fine too. In which case we could update the ureq case and leave everything else.
