### ISSUE TITLE
Add python as a target for bindings

### ISSUE THREAD

**Issue by tomerweller** [stellar/stellar-cli#1633]
Python is the second most used SDK in the Stellar ecosystem (after JS). It is often used by market makers and autogenerated bindings could reduce the cost of integration with defi protocols 

cc @overcat

**Comment by overcat** [comment]
That's indeed a great idea. I've added this to my TODO list.

**Comment by olivmath** [comment]
What is the current status of this issue?

I would like to do 🦀

**Comment by overcat** [comment]
Hi, @olivmath this issue requires some Python improvements, I will start working on the Python side this week  (I've been tied up with other projects lately).

If you're interested in contributing, feel free to check out other issues, or you can wait until I finish the Python improvements.

Thanks!

**Comment by overcat** [comment]
In Python SDK 12.0.0-beta4, we have significantly reduced the difficulty of calling contracts, and an example is provided in [the release notes](https://github.com/StellarCN/py-stellar-base/releases/tag/12.0.0-beta4). This also makes the subsequent work of creating bindings much simpler; we only need to extend [`ContractClient`](https://stellar-sdk.readthedocs.io/en/12.0.0-beta4/api.html#stellar_sdk.contract.ContractClient). 

cc @olivmath

**Comment by overcat** [comment]
I implemented it in Python, and I think we can add a Python option in stellar-cli and link to this project instead of adding another implementation in this repository?

See https://github.com/lightsail-network/stellar-contract-bindings

**Comment by janewang** [comment]
Thank you @overcat for this https://github.com/lightsail-network/stellar-contract-bindings

Closing this issue
