### ISSUE TITLE
Modify command for installing CLI

### ISSUE THREAD

**Issue by yskwmt** [stellar/stellar-cli#1782]
When I tried to install the Stellar CLI based on the instructions (https://developers.stellar.org/docs/build/smart-contracts/getting-started/setup), I found the below command did not work:
cargo install --locked stellar-cli --version v22.0.1 --features opt

I could successfully install the package 'stellar-cli v22.0.1' with the below command, simply removing 'v' from 'v22.0.1':
cargo install --locked stellar-cli --version 22.0.1 --features opt

**Comment by leighmcculloch** [comment]
Thanks for reporting! Fix is in progress here:
- https://github.com/stellar/stellar-docs/pulls/1116
