### ISSUE TITLE
Derive core version from go repo for e2e config

### ISSUE THREAD

**Issue by sreuland** [stellar/stellar-cli#328]
### What problem does your feature solve?
avoid manual property setting for core version in e2e settings as recommended here - https://github.com/stellar/soroban-tools/pull/310#discussion_r1050203983

### What would you like to see?
automated script that scrapes the core version from go repo

**Comment by janewang** [comment]
Is this ticket still relevant? We currently have: `stellar --version` which returns the version CLI is depending on. 

We also have `getVersionInfo` from the RPC which returns core version:
```
{
    "jsonrpc": "2.0",
    "id": 8675309,
    "result": {
        "version": "21.1.0-fcd2f0523f04279bae4502f3e3fa00ca627e6f6a",
        "commit_hash": "fcd2f0523f04279bae4502f3e3fa00ca627e6f6a",
        "build_time_stamp": "2024-05-10T11:18:38",
        "captive_core_version": "stellar-core 21.0.0.rc2 (c6f474133738ae5f6d11b07963ca841909210273)",
        "protocol_version": 21
    }
}
```
Are you suggesting surfacing this info on the CLI?

**Comment by leighmcculloch** [comment]
I don't think this issue is relevant to the CLI any longer. The version of the Go repo doesn't appear to be an input to the system tests in the e2e file any longer:
https://github.com/stellar/stellar-cli/blob/main/.github/workflows/e2e.yml
