### ISSUE TITLE
Add command for creating ledger snapshot

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-cli#383]
### What

Add a command for creating a ledger snapshot JSON file.

The ledger snapshot JSON file is the file format that the soroban-cli uses when in sandbox/local mode. The file format is also supported by the soroban-sdk in its test framework, and contract developers can load a ledger snapshot in a test by calling [`Env::from_snapshot_file(path)`](https://docs.rs/soroban-sdk/latest/soroban_sdk/struct.Env.html#method.from_snapshot_file). Contract developers can do this to get a ledger that has contracts and contract data in it, and write integration tests that execute their own contract alongside those other contracts.

### Why

To help developers create realistic integration test data for their contract tests, by helping them mirror pubnet/testnet data into their contract tests.

### Examples

Generate ledger.json containing all ledger entries of ledger 5.
```
$ soroban lab snapshot create --ledger 5
```

Generate ledger.json containing all ledger entries of ledger 5 that are owned by two contracts.
```
$ soroban lab snapshot create --ledger 5 --contract C1... --contract C2...
```

Generate ledger.json containing all ledger entries of ledger 5 that are owned by two contracts and one account.
```
$ soroban lab snapshot create --ledger 5 --contract C1... --contract C2... --account G1...
```

Generate ledger.json containing ledger entries of ledger 5 that have the given ledger keys.
```
$ soroban lab snapshot create --ledger 5 --ledger-key ...
```

**Comment by paulbellamy** [comment]
What would we be snapshotting here? Would this be something like?
1. Point soroban-cli at a remote soroban-rpc
2. Load all ledger entries from that
3. Save them locally

**Comment by leighmcculloch** [comment]
I updated the description with some CLI examples.

**Comment by leighmcculloch** [comment]
@paulbellamy it sounds like you're asking what the data source would be. I think we have several options:

1. `soroban-rpc` – soroban-cli asks soroban-rpc through its endpoints for ledger entries given ledger keys, and the rpc would probably need expanding to support some way of finding ledger keys.

3. `stellar-core` – core is able to download a set of buckets for a specific ledger since https://github.com/stellar/stellar-core/issues/3616 and it will also output as history archive json file. Another tool can parse the downloaded buckets.

5. archives – archives contain ledger entries and the soroban-cli could download them from an archive. In this case it is worth noting that there's no data verification, like what is optionally available in stellar-core when downloading a ledger.

After downloading the ledger entries from one of the above data sources, it would write them to a ledger snapshot file. The file format for that file is in the `soroban-ledger-snapshot` crate. The soroban-cli uses that crate for reading and writing its own `ledger.json`. The soroban-sdk supports loading an `Env` from a snapshot file, as well as writing one at anytime.

**Comment by leighmcculloch** [comment]
I'm inclined to think a good first stopping point is relying on stellar-core (point 2 above) because it will already compile a set of files that describe a single ledger. In it's most basic form the soroban-cli could simply take a set of buckets and convert them to a ledger snapshot json file. In an advanced form the soroban-cli would filter the ledger entries so the .json file is smaller and lightweight.
