### ISSUE TITLE
Stuck at installing soroban-cli v0.6.0 (Ubuntu - Windows WSL2)

### ISSUE THREAD

**Issue by darkvallen** [stellar/stellar-cli#466]
### What version are you using?
v0.6.0

### What did you do?
Installing soroban-cli using this command on Ubuntu-Windows WSL2

### What did you expect to see?
Installation Completed

### What did you see instead?
![Screenshot (56)](https://user-images.githubusercontent.com/117942738/222335066-1bd3d84e-f3b4-4e40-ae2f-12b4b17d0ac8.png)
Stuck at here,wasm-opt-sys(build) for more than 1 hour,i didnt experienced this when installing v0.4.0 version

**Comment by willemneal** [comment]
Yeah that crate uses c++. We should make a feature flag for it so that you could install without it.

**Comment by darkvallen** [comment]
> Yeah that crate uses c++. We should make a feature flag for it so that you could install without it.

Do you have any quick solution for it? so i could install it

**Comment by willemneal** [comment]
Som options:

1. Install it via windows and not wsl

2. Clone the repo and comment out the optimize command. 

3. Look up the wasm-opt project and see if there is anything about building on WSL.

**Comment by willemneal** [comment]
Here is the repo 

https://github.com/brson/wasm-opt-rs

So it could be a cmake or other C++ issue.

**Comment by janewang** [comment]
This issue is old. The current ways to install Stellar CLI is documented in README.
