### ISSUE TITLE
CLI: Add default public rpc for futurenet

### ISSUE THREAD

**Issue by willemneal** [stellar/stellar-cli#564]
### What problem does your feature solve?

Currently users have to manually add futurenet as a network, which unless using the new public endpoint was localhost. Now that we have a public instance we can default a network `futurenet` to point to it and allow users to reference a default futurenet network.

### What would you like to see?

Allow `futurenet` to be a default network such that you could add it with

```bash
soroban config network add --global --rpc-url https://rpc-futurenet.stellar.org:443/soroban/rpc --network-passphrase "Test SDF Future Network ; October 2022" futurenet
```

**Comment by leighmcculloch** [comment]
As part of this we should update the docs for futurenet deployment to use this flow rather than instructing people to run the docker quickstart image: https://github.com/stellar/soroban-tools/issues/564 (cc @tomerweller as I know you were thinking about this)

**Comment by waldmatias** [comment]
Related to this... if you currently run `soroban config network ls` it doesn't show any output (shouldn't default value be shown? e.g. localhost + config)
https://github.com/stellar/soroban-tools/blob/main/cmd/soroban-cli/src/commands/config/network/ls.rs
(just an usability defect, that will probably be solved if futurenet is set as default as per above)

**Comment by paulbellamy** [comment]
+100 on this. Would allow us to get users up-and-going much quicker. We could have the tutorial get them up to deploying and using a contract on futurenet right away, then get into "what is a network" later on.

**Comment by janewang** [comment]
This is done, for futurenet, testnet, and as well as passphrase for mainnet.
