### ISSUE TITLE
soroban-cli: `config network ls` should include magic "futurenet" network

### ISSUE THREAD

**Issue by paulbellamy** [stellar/stellar-cli#687]
https://github.com/stellar/soroban-tools/pull/642 added a new automatic network called "futurenet". However, that isn't currently included if you list networks with `config network ls`, but it should be.

cc @willemneal

**Comment by willemneal** [comment]
Sorry for the miscommunication but I added it as a default if one is not defined. So it will show up with `ls`, but it won't write the network to disc.

**Comment by leighmcculloch** [comment]
> So it will show up with `ls`

The default networks, and source account, don't appear to show when running `ls`.

This is what I see:

```console
❯ soroban config network ls

```

```console
❯ soroban config network ls --global

```

**Comment by stellarsaur** [comment]
With the latest changes on `main` I'm currently seeing `futurenet`:

```
./target/debug/soroban config network ls
futurenet
```

**Comment by janewang** [comment]
This is already working as expected with `stellar-network-ls`. Closing
